### PR TITLE
fix: remove the handle request call, since Symfony handles it by defa…

### PR DESCRIPTION
**Pull request by aarongerig**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no

This PR removes the `handleRequest` call for the login form, since it is not needed. Symfony does that already by default. If not removed, Symfony throws an error: `The CSRF token is invalid. Please try to resubmit the form.`.

### CODE REVIEW

**Comment by solverat** [comment]
@aarongerig are you sure about that?

**Comment by aarongerig** [comment]
@solverat I talked about that with @dpfaffenbauer and he told me so. Also I tested it on my instance and there it works now without error.

**Comment by solverat** [comment]
@aarongerig I'm unable to reproduce it. Using the handleRequest is still valid so i'm not sure about this. Could you provide me some more information?

**Comment by aarongerig** [comment]
@solverat So if you remove that `handleRequest` call, the login doesn't work for you anymore? Because I removed it on one of my projects and it still worked. Maybe @dpfaffenbauer could shed some light into this?

**Comment by solverat** [comment]
@aarongerig. It works with / without it. I did some research. Symfony uses a different approach to handle the login process (Authentication Provider). So yes, there is no need to handle the request (again). Could you please rebase this PR?

**Pull request merged**
